/* show jobs of employees */
SELECT ENAME, JOB FROM EMP;


/* number of employees per department */
SELECT DEPT.DNAME, COUNT(EMP.EMPNO) AS COUNT FROM DEPT
LEFT OUTER JOIN EMP ON EMP.DEPTNO = DEPT.DEPTNO
GROUP BY DEPT.DNAME;

/* average salary per job */
SELECT JOB, AVG(SAL) FROM EMP
GROUP BY JOB ORDER BY AVG(SAL) DESC;

/* min and max salary per job */
SELECT JOB, MIN(SAL), MAX(SAL) FROM EMP
GROUP BY JOB ORDER BY MIN(SAL) ASC;

/* summary salary per department */
SELECT DEPT.DNAME, SUM(SAL) FROM DEPT LEFT OUTER JOIN EMP ON EMP.DEPTNO = DEPT.DEPTNO
GROUP BY DEPT.DNAME;

/* form every possible manager pairs */
SELECT EMP1.ENAME, EMP1.JOB, EMP2.ENAME, EMP2.JOB FROM EMP EMP1 CROSS JOIN EMP EMP2
WHERE EMP1.JOB = 'MANAGER' AND EMP2.JOB = 'MANAGER' AND EMP1.EMPNO < EMP2.EMPNO;
